<template>
  <div v-if="loadingBudget" class="md-layout event-budget-section booking-section">
    <div class="text-center md-layout-item md-size-100" style="margin-top: 30vh">
      <radial-progress-bar
        innerStrokeColor="#A0A0A0"
        startColor="#f51355"
        stopColor="#f51355"
        :strokeWidth="3"
        :diameter="212"
        :completed-steps="completedProgressValue"
        :total-steps="100"
        :animateSpeed="5000"
        :isClockwise="false"
      >
        <div class="loading-budget-image">
          <img :src="`${$iconURL}Budget+Requirements/group-8494.svg`" />
        </div>
      </radial-progress-bar>
      <div class="text-transform-uppercase font-size-30 font-bold mt-4rem">Loading your budget breakdown</div>
      <div class="font-size-16 mt-2">
        Soon our smart algorithm will organize a budget breakdown based on hundreds of previous events we did
      </div>
    </div>
  </div>
  <div v-else class="md-layout event-budget-section booking-section">
    <vue-element-loading :active="isLoading" spinner="ring" color="#FF547C" />
    <budget-notifications></budget-notifications>
      <comment-editor-panel
          v-if="showCommentEditorPanel"
          :commentComponents="commentComponents"
          @saveComment="saveComment"
          @updateComment="updateComment"
          @deleteComment="deleteComment"
          @updateCommentComponent="updateCommentComponent"
      >
      </comment-editor-panel>
    <div class="event-page-header">
      <div class="md-layout-item md-size-100 event-header d-flex justify-content-between">
        <div class="header-name" style="width: max-content">
          <template v-if="currentStep !== 3">
            <h3 class="font-size-30 font-bold">
              <img :src="`${$iconURL}Concept/Asset 491.svg`" style="width: 30px; margin-right: 0.5em" />
              PLAN YOUR BUDGET
            </h3>
          </template>
          <template v-else>
            <h3 class="text-transform-uppercase">
              <img :src="`${this.$iconURL}budget+screen/SVG/Asset%2010.svg`" width="15" />
              APPROVE Budget breakdown
            </h3>
            <div class="text-transform-capitalize">An itemized budget, generated by our smart technology and based on thousands of real event quotes</div>
          </template>
        </div>
        <header-actions @toggleCommentMode="toggleCommentMode" @share="share" @export="exportToPdf"></header-actions>
      </div>
    </div>
    <div class="booking-header md-layout-item md-size-100" v-if="currentStep === 3">
      <event-budget-approve></event-budget-approve>
    </div>
    <div class="booking-header md-layout-item md-size-100" v-else>
      <event-budget-requirement-step1
        v-if="currentStep === 1"
        @change="setEventStep1"
        :defaultData="budgetInfo1"
      ></event-budget-requirement-step1>
      <event-budget-requirement-step2
        v-if="currentStep === 2"
        @change="setEventStep2"
        :defaultData="budgetInfo2"
      ></event-budget-requirement-step2>
    </div>
    <!--<vue-html2pdf-->
      <!--:show-layout="false"-->
      <!--:float-layout="true"-->
      <!--:enable-download="true"-->
      <!--:preview-modal="false"-->
      <!--:paginate-elements-by-height="1400"-->
      <!--:filename="`budget-${event.id}`"-->
      <!--:pdf-quality="2"-->
      <!--:manual-pagination="false"-->
      <!--pdf-format="a4"-->
      <!--pdf-orientation="portrait"-->
      <!--pdf-content-width="800px"-->
      <!--ref="html2Pdf"-->
      <!--&gt;-->
        <!--<section slot="pdf-content">-->
          <!--<div class="p-20 pdf-content">-->
              <!--<h3 class="font-bold-extra font-size-30">-->
                  <!--<img :src="`/static/icons/budget/budget.png`" width="15" />-->
                  <!--Budget-->
              <!--</h3>-->
              <!--<div class="card-section card-overview" style="border: solid 2px #dbdbdb !important">-->
                  <!--<div class="section-header" style="border-bottom: solid 2px #dbdbdb !important">Overview</div>-->
                  <!--<div class="budget-list d-flex justify-content-between">-->
                      <!--<div class="budget-list__item">-->
                          <!--<div class="label-title">Budget</div>-->
                          <!--<div class="budget-value">${{ budgetStatistics.total | withComma(Number) }}</div>-->
                          <!--<md-button v-if="canEdit" class="md-rose md-simple md-sm edit-budget" @click="showBudgetModal = true"-->
                          <!--&gt;Edit</md-button-->
                          <!--&gt;-->
                      <!--</div>-->
                      <!--<div class="budget-list__item">-->
                          <!--<div class="label-title">Allocated</div>-->
                          <!--<div class="budget-value">${{ budgetStatistics.allocated | withComma(Number) }}</div>-->
                          <!--<div class="percent">{{ budgetStatistics.allocatedPercentage }} %</div>-->
                      <!--</div>-->
                      <!--<div class="budget-list__item">-->
                          <!--<div class="label-title">Booked</div>-->
                          <!--<div class="budget-value">${{ budgetStatistics.booked | withComma(Number) }}</div>-->
                          <!--<div class="percent">{{ budgetStatistics.bookedPercentage }}%</div>-->
                      <!--</div>-->
                  <!--</div>-->
              <!--</div>-->
              <!--<div class="card-section card-overview-saved text-center">-->
                  <!--<span>So far you saved :</span>-->
                  <!--<md-icon class="card-overview-saved-icon" style="color: #167c3a" v-if="budgetStatistics.saved >= 0"-->
                  <!--&gt;add_circle_outline</md-icon-->
                  <!--&gt;-->
                  <!--<md-icon class="card-overview-saved-icon color-red" v-else>remove_circle_outline</md-icon>-->
                  <!--<span class="card-overview-saved-amount">$ {{ budgetStatistics.saved | withComma(Number) }}</span>-->
              <!--</div>-->
              <!--<div class="card-section card-expense" style="border: solid 2px #dbdbdb !important">-->
                  <!--<div class="section-header" style="border-bottom: solid 2px #dbdbdb !important">Expenses</div>-->
                  <!--<div>-->
                      <!--<pie-chart-round :event.sync="event" :items="pieChartData" :showImage="true"></pie-chart-round>-->
                  <!--</div>-->
              <!--</div>-->
          <!--</div>-->
          <!--<div class="html2pdf__page-break"></div>-->
          <!--<div class="p-20 event-blocks-table">-->
              <!--<label class="font-size-26 font-bold">Total</label>-->
              <!--<event-budget-vendors-->
                  <!--:event.sync="event"-->
                  <!--:event-components="selectedComponents"-->
                  <!--:editingMode="false"-->
                  <!--type="total"-->
                  <!--@change="onChangeComponent"-->
                  <!--@add="onAddMoreBudget"-->
              <!--&gt;</event-budget-vendors>-->
          <!--</div>-->
          <!--<div class="html2pdf__page-break"></div>-->
          <!--<div class="p-20 event-blocks-table">-->
              <!--<label class="font-size-26 font-bold">Per Guest</label>-->
              <!--<event-budget-vendors-->
                  <!--:event.sync="event"-->
                  <!--:event-components="selectedComponents"-->
                  <!--:editingMode="false"-->
                  <!--type="perGuest"-->
                  <!--@change="onChangeComponent"-->
                  <!--@add="onAddMoreBudget"-->
              <!--&gt;</event-budget-vendors>-->
          <!--</div>-->
          <!--</section>-->
    <!--</vue-html2pdf>-->
    <div class="wizard-footer d-flex">
      <div>
        <md-button @click="back" class="md-black md-maryoku md-simple">
          <md-icon>keyboard_backspace</md-icon>
          Back
        </md-button>
        <md-button @click="scrollToTop" class="md-button md-simple md-just-icon md-theme-default scroll-top-button">
          <img :src="`${$iconURL}Budget+Requirements/Asset+49.svg`" width="17" />
        </md-button>
      </div>
      <div class="status" v-if="currentStep < 3">
        <div class="status-step">{{ this.currentStep }} Step of 2</div>
        <md-progress-bar
          class="md-red progress-bar"
          md-mode="determinate"
          :md-value="(this.currentStep / 2) * 100"
        ></md-progress-bar>
      </div>
      <div class="footer-actions" v-if="currentStep < 3">
        <md-button
          @click="skip"
          class="md-black md-maryoku md-simple"
          @mouseover="skipToolTip = true"
          @mouseleave="skipToolTip = false"
        >
          Skip
          <md-icon>keyboard_arrow_right</md-icon>
        </md-button>
        <md-button @click="next" class="md-default md-red md-maryoku next-btn">Next</md-button>
      </div>
      <div class="footer-actions" v-else>
        <span style="line-height: 56px; padding-right: 30px">
          <img :src="`${$iconURL}Event%20Page/light.svg`" width="27" />
          You can edit this anytime
        </span>
        <md-button @click="next" class="md-default md-red md-maryoku">Approve Budget Breakdown</md-button>
      </div>
    </div>
  </div>
</template>
<script>
import RadialProgressBar from "vue-radial-progress";

import CommentEditorPanel from "./CommentEditorPanel";
import VueElementLoading from "vue-element-loading";
import {CommentMixins, ShareMixins} from "@/mixins";
import HeaderActions from "@/components/HeaderActions";
import EventBudgetRequirementStep1 from "./EventBudgetRequirementStep1";
import EventBudgetRequirementStep2 from "./EventBudgetRequirementStep2";
import EventBudgetApprove from "./EventBudgetApprove.vue";

import { BUDGET_MESSAGES } from "@/constants/messages";
import EventComponent from "@/models/EventComponent";
import Calendar from "@/models/Calendar";
import CalendarEvent from "@/models/CalendarEvent";
import moment from "moment";
import EventBudgetVendors from "./EventBudgetVendors";
import PieChartRound from "./PieChartRound.vue";
import {mapMutations, mapGetters} from "vuex";
const VueHtml2pdf = () => import("vue-html2pdf");

export default {
  components: {
    CommentEditorPanel,
    VueElementLoading,
    HeaderActions,
    EventBudgetRequirementStep1,
    EventBudgetRequirementStep2,
    EventBudgetApprove,
    RadialProgressBar,
    EventBudgetVendors,
    PieChartRound,
    VueHtml2pdf
  },
  mixins: [CommentMixins, ShareMixins],
  data() {
    return {
      editingEvent: {},
      isLoading: false,
      showCommentEditorPanel: false,
      currentStep: 1,
      loadingBudget: false,
      approveBudget: false,
      budgetInfo1: {},
      budgetInfo2: {},
      completedProgressValue: 0,
      selectedComponents: [],
      showBudgetModal: false,
    };
  },
  async mounted() {
    this.currentStep = this.event.budgetProgress >= 50 ? 3 : 1;
      // notify budget states
      if (this.showBudgetNotification.indexOf(this.event.id) === -1) {
          // this.notifyStates();
          this.setBudgetNotification(this.event.id);
      }
    await this.getEventComponents();
    this.$root.$on('budget_notification_action', message => {
        let obj = BUDGET_MESSAGES.find(m => m.title = message);
        if (obj.key === 'not_approved') this.next();
    })
  },
  methods: {
    ...mapMutations("event", ["setBudgetNotification",]),
    getCalendar() {
      return new Calendar({ id: this.currentUser.profile.defaultCalendarId });
    },
    toggleCommentMode(mode) {
      this.showCommentEditorPanel = mode;
    },
    exportToPdf() {
      this.$refs.html2Pdf.generatePdf();
    },
    back() {
      if (this.currentStep !== 1) {
        this.currentStep -= 1;
      }
    },
    next() {
      if (this.currentStep === 3) {
        const event = new CalendarEvent({
          id: this.event.id,
          calendar: new Calendar({ id: this.event.calendar.id }),
          budgetProgress: 100,
          approvedBudget: this.event.totalBudget,
        });
        this.$store.dispatch("event/saveEventAction", event).then((res) => {
          this.$router.push({ path: `/events/${this.event.id}/edit/budget` });
        });
      } else if (this.currentStep === 2) {
        const event = new CalendarEvent({
          id: this.event.id,
          calendar: new Calendar({ id: this.event.calendar.id }),
          budgetProgress: 50,
          totalBudget: this.editingEvent.totalBudget ? this.editingEvent.totalBudget : 0,
          noBudget: this.editingEvent.noBudget,
          reCalculate: true,
          eventDecisionFactor3: this.editingEvent.eventDecisionFactor3,
          eventMovieId: this.editingEvent.eventMovieId,
        });
        this.loadingBudget = true;
        this.$store.dispatch("event/saveEventAction", event).then((res) => {
          this.completedProgressValue = 100;
          setTimeout(() => {
            this.loadingBudget = false;
            this.completedProgressValue = 0;
            this.currentStep += 1;
          }, 5000);
        });
      } else {
        this.currentStep += 1;
      }
    },
    skip() {},
    scrollToTop() {
      window.scrollTo(0, 0);
    },
    setEventStep1(eventInfo) {
      console.log(eventInfo);
      this.editingEvent.totalBudget = eventInfo.noBudget ? 0 : eventInfo.budget;
      this.editingEvent.eventDecisionFactor3 = eventInfo.selectedLevel;
      this.editingEvent.noBudget = eventInfo.noBudget;
      this.budgetInfo1 = eventInfo;
    },
    setEventStep2(eventInfo) {
      console.log(eventInfo);
      this.budgetInfo2 = eventInfo;
      this.editingEvent.eventMovieId = eventInfo.label;
    },
    notifyStates() {
        console.log('checkMessageStatus')
          this.budgetStates = [];
          let now = moment();
          let created_at = moment(this.event.dateCreated);
          if (this.event.budgetProgress === 50 && now.diff(created_at, "days") > 15) {
              this.budgetStates.push({ key: "not_approved" });
          }

          if (this.budgetStates.length) {
              this.budgetStates.map((it) => {
                  let message_item = BUDGET_MESSAGES.find((m) => m.key == it.key);
                  this.$notify({
                      message: {
                          title: message_item.title,
                          content: message_item.message,
                          action: message_item.action,
                      },
                      icon: `${this.$iconURL}messages/${message_item.icon}`,
                      horizontalAlign: "right",
                      verticalAlign: "top",
                      type: message_item.type,
                      timeout: 5000,
                  });
              });
          }
      },
    getEventComponents: async function () {
      let event = new CalendarEvent({ id: this.event.id });
      let _calendar = this.getCalendar();
      let eventComponent = new EventComponent().for(_calendar, event);
      let components = await eventComponent.get();
      console.log("getEventComponents", components);
      components.sort((a, b) => a.order - b.order);
      console.log(components);
      this.event.components = components;
      this.selectedComponents = components;
    },
    onChangeComponent(event) {
      // this.loadEventData("update");
    },
    onAddMoreBudget(value) {
      // this.newBudget = `${this.event.totalBudget + value}`.replace(/\D/g, "").replace(/\B(?=(\d{3})+(?!\d))/g, ",");
      // this.updateBudget();
    },
  },
  computed: {
    ...mapGetters({
        showBudgetNotification: "event/showBudgetNotification",
        budgetStatistics: "event/budgetStatistics",
        currentUser: "auth/currentUser",
    }),
    canEdit() {
      return !this.permission || this.permission === "edit";
    },
    event() {
      return this.$store.state.event.eventData;
    },
    categoryList() {
      return this.$store.state.event.eventData.components.sort((a, b) => a.eventCategory.order - b.eventCategory.order);
    },
    pieChartData() {
      return this.categoryList.filter((item) => item.componentId !== "unexpected");
    },
  },
};
</script>
<style lang="scss" scoped>
.event-budget-section {
  .event-book-requirement-header {
    img {
      width: 100%;
      object-fit: cover;
    }
  }
  .wizard-footer {
    padding: 10px 40px;

    .status {
      text-align: center;
      transform: translateY(-35%);
      .status-step {
        margin-bottom: 10px;
      }
    }
  }
  .radial-progress-container {
    margin: auto;
  }
}
.loading-budget-image {
  width: 200px;
  height: 200px;
  margin: auto;
  border-radius: 50%;
  // border: solid 3px #f51355;
  background-color: #ffffff;
  img {
    margin-top: 50%;
    transform: translate(10px, -50%);
  }
}
</style>
