export const timelineBlockItems = [
    [
        {
            id: 1,
            buildingBlockType: "setup",
            eventCategory: [
                'venuerental'
            ],
            icon: "Setup",
            color: "#ffc001",
        },
        {
            id: 5,
            buildingBlockType: "Transportation",
            eventCategory: ['transportation'],
            icon: "Transportation",
            color: "#44546a",
        },
    ],

    [
        {
            id: 2,
            buildingBlockType: "activity",
            icon: "Activity",
            color: "#20c997",
            eventCategory: ['entertainment'],
        },
        {
            id: 8,
            buildingBlockType: "Show",
            icon: "Show",
            color: "#00bcd4",
            eventCategory: ['entertainment'],
        },
        {
            id: 9,
            buildingBlockType: "Speaker / Keynote",
            icon: "speaker",
            color: "#641956",
            eventCategory: ['entertainment'],
        },

        {
            id: 4,
            buildingBlockType: "Discussion",
            icon: "Discussion",
            color: "#3a3838",
            eventCategory: ['meetingorganizationfees'],
        },
    ],

    [
        {
            id: 10,
            buildingBlockType: "Break",
            icon: "Break",
            color: "#ff527c",
            eventCategory: ['entertainment'],
        },
        {
            id: 6,
            buildingBlockType: "Relaxation",
            icon: "Relaxation",
            color: "#0caf50",
            eventCategory: ['entertainment'],
        },
        {
            id: 3,
            buildingBlockType: "meal",
            icon: "Meal",
            color: "#f44336",
            eventCategory: ['foodandbeverage'],
        },
    ],

    [
        {
            id: 7,
            buildingBlockType: "Other",
            icon: "other",
            color: "#a5a5a5",
        },
    ],
];

export const timelineTempates = [
    { name: "registration", type: "group" },
    { name: "activity-1", type: "group" },
    { name: "meal", type: "group" },
    { name: "activity-2", type: "group" },
    { name: "summary", type: "group" },
];

export const serviceCategoryImages = {
    "venuerental": [
        "Venue+Type/Academic Venue_Shutterstock.jpg",
        "Venue+Type/Bar or Pub or Club_Shutterstock.jpg",
        "Venue+Type/Community Center_Shutterstock.jpg",
        "Venue+Type/Gallery_Option 1_Canva Free.png",
        "Venue+Type/Garden_Option 1_Shutterstock.jpg",
        "Venue+Type/Historic Establishment_Canva Pro.png",
        "Venue+Type/Meeting Room_Shutterstock.jpg",
        "Venue+Type/Restaurant_Shutterstock.jpg",
        "Venue+Type/Sports Club_Shutterstock.jpg",
        "Venue+Type/Stadium_Shutterstock.jpg",
        "Venue+Type/Stately Home_Option 1_Shutterstock.jpg",
    ],
    "foodandbeverage": [
        "Beverage/Beer_Canva Pro.png",
        "Beverage/Bourbon_Canva Pro.png",
        "Beverage/Champagne_Canva Pro.png",
        "Beverage/Cocktail_Canva Pro.png",
        "Beverage/Coffee _ Dream_Canva Pro.png",
        "Beverage/Margarita_Canva Pro.png",
        "Beverage/Martini_Canva Pro.png",
        "Beverage/Mixology_Canva Pro.png",
        "Beverage/Rum_Canva Pro.png",
        "Beverage/Soft Drinks_Option 1_Canva Pro.png",
        "Beverage/Soft Drinks_Option 2_Canva Pro.png",
        "Beverage/Sparkling Water_Canva Pro.png",
        "Beverage/Still Water_Canva Pro.png",
        "Beverage/Tequila_Canva Pro.png",
        "Beverage/Vodka_Canva Pro.png",
        "Beverage/Whiskey_Canva Pro.png",
        "Beverage/Wine_Canva Pro.png",
    ],
    "entertainment": [
        "Staff/Concierge 2.png",
        "Staff/Day Of Coordinator Option 2.jpg",
        "Staff/Event Model 1.png",
        "Staff/Event Registration 1.png",
        "Staff/shutterstock_72321160.jpg",
        "Staff/Transportation Host.png",
        "Staff/Wait Staff 1.png",
    ],
    "equipmentrentals": [
        "Staff/Concierge 2.png",
        "Staff/Day Of Coordinator Option 2.jpg",
        "Staff/Event Model 1.png",
        "Staff/Event Registration 1.png",
        "Staff/shutterstock_72321160.jpg",
        "Staff/Transportation Host.png",
        "Staff/Wait Staff 1.png",
    ],
    "securityservices": [
        "Staff/Concierge 2.png",
        "Staff/Day Of Coordinator Option 2.jpg",
        "Staff/Event Model 1.png",
        "Staff/Event Registration 1.png",
        "Staff/shutterstock_72321160.jpg",
        "Staff/Transportation Host.png",
        "Staff/Wait Staff 1.png",
    ],
    "giveaways": [
        "Giveaways/Apparel_Canva Pro.png",
        "Giveaways/Ceremonial Items_Canva Pro.png",
        "Giveaways/Drinkware_Canva Pro.png",
        "Giveaways/Fitness_Canva Pro.png",
        "Giveaways/Gadgets - Option2.jpg",
        "Giveaways/Gadgets.png",
        "Giveaways/Office Items_Canva Pro.png",
        "Giveaways/Specialty Food _ Liquor_Canva Pro.png",
        "Giveaways/Tote Bags_Canva Pro.png",
        "Giveaways/Travel Accessories_Canva Pro.png",
        "Giveaways/Travel Accessories_Option 2.jpg",
        "Giveaways/Wellness_Canva Pro.png",
    ],
    "videographyandphotography": [
        "Photography+_+Videography/Black_White.jpg",
        "Photography+_+Videography/Buisness.jpg",
        "Photography+_+Videography/Candid.jpg",
        "Photography+_+Videography/Commercial.jpg",
        "Photography+_+Videography/Drone.jpg",
        "Photography+_+Videography/Portrait.jpg",
    ],
    "advertising-promotion": [
        "Indoor Activities/Casino Games 2.png",
        "Indoor Activities/Indoor Sport.png",
        "Indoor Activities/Make Your Own.png",
        "Indoor Activities/Photo Booth 2.png",
    ],
    "audiovisualstagingservices": [
        "A-V/Lighting_Shutterstock.jpg",
        "A-V/Plasma TV_Canva Pro.png",
        "A-V/Projector_Shutterstock.jpg",
    ],
    "signageprinting": [
        "A-V/Lighting_Shutterstock.jpg",
        "A-V/Plasma TV_Canva Pro.png",
        "A-V/Projector_Shutterstock.jpg",
    ],
    "administration": [
        "A-V/Lighting_Shutterstock.jpg",
        "A-V/Plasma TV_Canva Pro.png",
        "A-V/Projector_Shutterstock.jpg",
    ],
    "meetingorganizationfees": ["A-V/Lighting_Shutterstock.jpg",
        "A-V/Plasma TV_Canva Pro.png",
        "A-V/Projector_Shutterstock.jpg",],
    "transportation": [
        "Transportation/Air Services_Canva Pro.png",
        "Transportation/ATV_Canva Pro.png",
        "Transportation/Bicycle_Canva Pro.png",
        "Transportation/Boat_Canva Pro.png",
        "Transportation/Bus_Canva Pro.png",
        "Transportation/Ferry_Canva Pro.png",
        "Transportation/Gold Carts_Canva Pro.png",
        "Transportation/Private Black Car.jpg",
        "Transportation/Van_Canva Pro.png",
    ],
    "decor": [
        "Decor/Florals_Option 1_Canva Pro.png",
        "Decor/Interior Design_Canva Free.png",
        "Decor/Lighting_Canva Pro.png",
    ],
    "shipping": [
        "A-V/Lighting_Shutterstock.jpg",
        "A-V/Plasma TV_Canva Pro.png",
        "A-V/Projector_Shutterstock.jpg",
    ],
    "other": [],
}

export const ServiceCards = [
    [
        [
            {
                name: "Venue Type",
                serviceCategory: "venuerental",
                images: [
                    "Venue+Type/Academic Venue.jpg",
                    "Venue+Type/Bar or Pub or Club.jpg",
                    "Venue+Type/Community Center.jpg",
                    "Venue+Type/Gallery_Option.png",
                    "Venue+Type/Garden.jpg",
                    "Venue+Type/Historic Establishment.png",
                    "Venue+Type/Meeting Room.jpg",
                    "Venue+Type/Restaurant.jpg",
                    "Venue+Type/Sports Club.jpg",
                    "Venue+Type/Stadium.jpg",
                    "Venue+Type/Stately Home.jpg",
                ],
                imageTitles: [
                    "Academic Venue",
                    "Bar or Pub or Club",
                    "Community Center",
                    "Gallery",
                    "Garden",
                    "Historic Establishmen",
                    "Meeting Room",
                    "Restaurant",
                    "Sports Club",
                    "Stadium",
                    "Stately Home",
                ],
                icon: "NewRequirements/Group 18008.svg",
            },
            {
                name: "Decor",
                serviceCategory: "decor",
                images: ["Decor/Florals.png", "Decor/Interior Design.png", "Decor/Lighting.png"],
                imageTitles: ["Florals", "Interior Design", "Lighting"],
                icon: "NewRequirements/Group 18012.svg",
            },
        ],
        [
            {
                name: "Cuisine Speciality",
                serviceCategory: "foodandbeverage",
                script:
                "requirements['multi-selection'][0]['options'][0]['selected'] = true;requirements['multi-selection'][0]['options'][1]['selected'] = false",
                images: [
                    "Cuisine/American Food.png",
                    "Cuisine/Argentine Food.png",
                    "Cuisine/Chinese Food.jpg",
                    "Cuisine/Colombian Food.png",
                    "Cuisine/Cuban Food.jpg",
                    "Cuisine/French Food.png",
                    "Cuisine/German Food.png",
                    "Cuisine/Greek Food.png",
                    "Cuisine/Indian Food.png",
                    "Cuisine/Italian Food.png",
                    "Cuisine/Japanese Food.png",
                    "Cuisine/Mexican Food.png",
                    "Cuisine/Peruvian Food.png",
                    "Cuisine/Spanish Food.png",
                    "Cuisine/Thai Food.jpg",
                ],
                imageTitles: [
                    "American Food",
                    "Argentine Food",
                    "Chinese Food",
                    "Colombian Food",
                    "Cuban Food",
                    "French Food",
                    "German Food",
                    "Greek Food",
                    "Indian Food",
                    "Italian Food",
                    "Japanese Food",
                    "Mexican Food",
                    "Peruvian Food",
                    "Spanish Food",
                    "Thai Food",
                ],
                icon: "NewRequirements/Group 18012.svg",
            },
            {
                name: "Liquor Stations",
                serviceCategory: "foodandbeverage",
                script:
                "requirements['multi-selection'][0]['options'][0]['selected'] = false;requirements['multi-selection'][0]['options'][1]['selected'] = true",
                images: [
                    "Beverage/Beer.png",
                    "Beverage/Bourbon.png",
                    "Beverage/Champagne.png",
                    "Beverage/Cocktail.png",
                    "Beverage/Coffee and Tea.png",
                    "Beverage/Margarita.png",
                    "Beverage/Martini.png",
                    "Beverage/Mixology.png",
                    "Beverage/Rum.png",
                    "Beverage/Soft Drinks.png",
                    "Beverage/Sparkling Water.png",
                    "Beverage/Still Water.png",
                    "Beverage/Tequila.png",
                    "Beverage/Vodka.png",
                    "Beverage/Whiskey.png",
                    "Beverage/Wine.png",
                ],
                imageTitles: [
                    "Beer",
                    "Bourbon",
                    "Champagne",
                    "Cocktail",
                    "Coffee Dream",
                    "Margarita",
                    "Martini",
                    "Mixology",
                    "Rum",
                    "Soft Drinks",
                    "Sparkling Water",
                    "Still Water",
                    "Tequila",
                    "Vodka",
                    "Whiskey",
                    "Wine",
                ],
                icon: "NewRequirements/Group 18017.svg",
            },
        ],
        [
            {
                name: "Photography  Videography",
                serviceCategory: "videographyandphotography",
                images: [
                    "Photography+_+Videography/Black_White.jpg",
                    "Photography+_+Videography/Buisness.jpg",
                    "Photography+_+Videography/Candid.jpg",
                    "Photography+_+Videography/Commercial.jpg",
                    "Photography+_+Videography/Drone.jpg",
                    "Photography+_+Videography/Portrait.jpg",
                ],
                imageTitles: ["Black White", "Buisness", "Candid", "Commercial", "Drone", "Portrait"],
                icon: "NewRequirements/Group 18009.svg",
            },
            {
                name: "Music",
                serviceCategory: "entertainment",
                musicPlayer: true,
                clips: [
                    "Music Clips/Asian-india-Bensound.mp3",
                    "Music Clips/Blues-hipjazz-Bensound.mp3",
                    "Music Clips/Classical_Wake_Up_CC Sound.mp3",
                    "Music Clips/Country_Country Boy Song-Bensound.mp3",
                    "Music Clips/Electronic_ERF-Bensound.mp3",
                    "Music Clips/Folk_Hey-Bensound.mp3",
                    "Music Clips/Hip Hop-groovyhiphop-Bensound.mp3",
                    "Music Clips/Jazz-thejazzpiano-Bensound.mp3",
                    "Music Clips/Latin_Latin Beat_CC Hound.mp3",
                    "Music Clips/pop_Funday-Bensound.mp3",
                    "Music Clips/RB_Heart_CC Sound.mp3",
                    "Music Clips/Rock-rumble-Bensound.mp3",
                    "Music Clips/Soul-retrosoul-Bensound.mp3",
                ],
                clipTitles: [
                    "Asian",
                    "Blues",
                    "Classical",
                    "Country",
                    "Electronic",
                    "Folk",
                    "Hip Hop",
                    "Jazz",
                    "Latin Beat",
                    "Pop Funday",
                    "RB Heart",
                    "Rock",
                    "Soul",
                ],
                images: [
                    "Asian.jpg",
                    "Blues.jpg",
                    "Classic.jpg",
                    "Country.jpg",
                    "Electronic.jpg",
                    "Folk.jpg",
                    "Hip Hop.jpg",
                    "Jazz.jpg",
                    "Latin.jpg",
                    "pop.jpg",
                    "RB.jpg",
                    "Rock.jpg",
                    "SOUL.jpg",
                ],
                imageTitles: ["Black White", "Buisness", "Candid", "Commercial", "Drone", "Portrait"],
                icon: "NewRequirements/Group 18013.svg",
                script: `
                  requirements['multi-selection'][0]['options'].forEach(item=>item.selected = false)
                  requirements['multi-selection'][0]['options'][0]['selected'] = true;
                  requirements['multi-selection'][0]['options'][1]['selected'] = true;
                `,
            },
        ],
    ],
    [
        [
            {
                name: "Giveaways",
                serviceCategory: "giveaways",
                images: [
                    "Giveaways/Apparel.png",
                    "Giveaways/Ceremonial Items.png",
                    "Giveaways/Drinkware.jpeg",
                    "Giveaways/Fitness.jpeg",
                    "Giveaways/Gadgets.jpeg",
                    "Giveaways/Office Items.png",
                    "Giveaways/Specialty Food and Liquor.png",
                    "Giveaways/Tote Bags.png",
                    "Giveaways/Travel Accessories.jpg",
                    "Giveaways/Wellness.png",
                ],
                imageTitles: [
                    "Apparel",
                    "Ceremonial Items",
                    "Drinkware",
                    "Fitness",
                    "Gadgets",
                    "Office Items",
                    "Specialty Food and Liquor",
                    "Tote Bags",
                    "Travel Accessories",
                    "Wellness",
                ],
                icon: "NewRequirements/Group 18014.svg",
            },
            {
                name: "Indoor Activities",
                serviceCategory: "entertainment",
                images: [
                    "Indoor Activities/Casino Games.png",
                    "Indoor Activities/Indoor Sport.png",
                    "Indoor Activities/Make Your Own.png",
                    "Indoor Activities/Photo Booth.png",
                ],
                imageTitles: ["Casino Games", "Indoor Sport", "Make Your Own", "Photo Booth"],
                icon: "NewRequirements/Group 18012.svg",
                script: `
                  requirements['multi-selection'][0]['options'].forEach(item=>item.selected = false)
                  requirements['multi-selection'][0]['options'][2]['selected'] = true;
                `,
            },
        ],
        [
            {
                name: "Outdoor Activities",
                serviceCategory: "entertainment",
                images: [
                    "Outdoor Activities/class.jpg",
                    "Outdoor Activities/Day trip_option.png",
                    "Outdoor Activities/Museum & Art Gallery Visit.png",
                    "Outdoor Activities/Show.jpg",
                    "Outdoor Activities/Site Seeing.jpg",
                    "Outdoor Activities/Sport Event.png",
                    "Outdoor Activities/Wine Tasting.jpg",
                    "Outdoor Activities/workshop.jpg",
                ],
                imageTitles: [
                    "Class",
                    "Day Trip Option",
                    "Museum & Art Gallery Visit",
                    "Show",
                    "Site Seeing",
                    "Sport Event",
                    "Wine Tasting",
                    "Workshop",
                ],
                icon: "NewRequirements/Group 18010.svg",
                script: `
                  requirements['multi-selection'][0]['options'].forEach(item=>item.selected = false)
                  requirements['multi-selection'][0]['options'][3]['selected'] = true;
                `,
            },
            {
                name: "AV",
                serviceCategory: "audiovisualstagingservices",
                images: ["A-V/Lighting.jpg", "A-V/Plasma TV.jpeg", "A-V/Projector.jpg"],
                imageTitles: ["Lighting", "Plasma TV", "Projector"],
                icon: "NewRequirements/Group 18073.svg",
            },
        ],
        [
            {
                name: "Guest Serivces & Staffing",
                serviceCategory: "administration",
                images: [
                    "Staff/Concierge.png",
                    "Staff/Day Of Coordinator.jpg",
                    "Staff/Event Model.png",
                    "Staff/Event Registration.png",
                    "Staff/Tour Guide.jpg",
                    "Staff/Transportation Host.png",
                    "Staff/Wait Staff.png",
                ],
                imageTitles: [
                    "Concierge",
                    "Day Of Coordinator",
                    "Event Model",
                    "Event Registration",
                    "Tour Guide",
                    "Transportation Host",
                    "Wait Staff",
                ],
                icon: "NewRequirements/Group 18026.svg",
            },
            //  {
            //   name: "Transportation",
            //   serviceCategory: "transportation",
            //   images: [
            //     "Transportation/Air Services.png",
            //     "Transportation/ATV.png",
            //     "Transportation/Bicycle.png",
            //     "Transportation/Boat.png",
            //     "Transportation/Bus.png",
            //     "Transportation/Ferry.png",
            //     "Transportation/Gold Carts.png",
            //     "Transportation/Private Black Car.jpg",
            //     "Transportation/Van.png",
            //   ],
            //   imageTitles: [
            //     "Air Services",
            //     "ATV",
            //     "Bicycle",
            //     "Boat",
            //     "Bus",
            //     "Ferry",
            //     "Gold Carts",
            //     "Private Black Car",
            //     "Van",
            //   ],
            //   icon: "NewRequirements/Group 18016.svg",
            // },
            {
                name: "Equipment Rentals",
                serviceCategory: "equipmentrentals",
                images: ["Rentals/Furniture.jpg", "Rentals/Tech Equpiment.jpg", "Rentals/Tent.jpg"],
                imageTitles: ["Furniture", "Tech Equipment", "Tent"],
                icon: "NewRequirements/Group 18016.svg",
            },
        ],
    ],
]
