export const backgroundImages = ['load_0.jpg', 'load_1.jpg', 'load_2.jpg', 'load_3.jpg', 'load_4.jpg', 'load_5.jpg', 'load_6.jpg', 'load_7.jpg'];
export const quotes = [
  { description: "“The power of imagination makes us infinite.”", author: " - John Muir"},
  { description: "“Somewhere, something incredible is waiting to be known.”", author: " – Sharon Begley"},
  { description: "“The best preparation for tomorrow is doing your best today.” ", author: " – H. Jackson Brown, Jr."},
  { description: "“Grant that I may always desire more than I can accomplish.” ", author: " – Michaelangelo"},
  { description: "“Never look back unless you are planning on going that way.” ", author: " – Henry David Thoreau"},
  { description: "“Today is the only day. Yesterday is gone.” ", author: "– John Wooden"},
  { description: "“Before everything else, getting ready is the secret of success.”", author: "  – Henry Ford"},
  { description: "“The best way out is always through.” – Robert Frost", author: " – Robert Frost"},
  { description: "“Vitality shows in not only the ability to persist but the ability to start over.” ", author: " – F. Scott Fitzgerald"},
  { description: "“Don’t find fault. Find a remedy.” ", author: " -Henry Ford"},
  { description: "“By failing to prepare, you are preparing to fail.", author: "- John Muir"},
  { description: "The art of being wise is the art of knowing what to overlook.” ", author: " -William James"},
  { description: "Plans are only good intentions unless they immediately degenerate into hard work.”", author: " - Peter Drucker"},
  { description: "“If you always do what you always did, you will always get what you always got.” ", author: "- Albert Einstein"},
  { description: "“Simplicity is the ultimate sophistication.” ", author: "- Leonardo Da Vinci"},
  { description: "“Nothing will work unless you do.”", author: "- Maya Angelou"},
  { description: "“Forget about making mistakes, just do it.” ", author: "- Ajaero Tony Martins"},
  { description: "“The greatest mistake you can make in life is to be continually fearing you will make one.”", author: "- Elbert Hubbard"},
  { description: "“The only way to do great work is to love what you do.”", author: "- Steve Jobs"},
  { description: "“Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.”", author: "- Jamie Paolinetti"},
  { description: "“When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.”", author: "- Henry For"},
  { description: "“If you treat every situation as a life and death matter, you’ll die a lot of times.”", author: "- Dean Smith"},
  { description: "“Perfection is not attainable, but if we chase perfection we can catch excellence.”", author: "- Vince Lombardi"},
  { description: "“I can’t change the direction of the wind, but I can adjust my sails to always reach my destination.”", author: "- James Dean"},
  { description: "“A goal without a plan is just a wish.”", author: "- Antoine de Saint-Exupéry"},
  { description: "Some people look for a beautiful place. Others make a place beautiful.”", author: "- Hazrat Inavat Khan"},
  { description: "“To achieve great things, two things are needed: a plan and not quite enough time.”", author: "- Leonard Bernstein"},
]